services:
  - type: web
    name: portfolio-web
    runtime: python
    buildCommand: |
      poetry install --no-dev
      poetry run python manage.py collectstatic --no-input
    startCommand: "poetry run gunicorn milon_base.wsgi:application"
    pythonVersion: 3.12
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true